-- The single table this microservice owns.
--
-- id            : the permanent identity of a user. A 64-bit Snowflake ID
--                 (time-ordered integer) generated by the service, so BIGINT.
--                 Primary key, so it is automatically NOT NULL, UNIQUE, indexed.
-- email         : the lookup key for GET/DELETE. UNIQUE so two users can never
--                 share it (and the DB builds an index for us to enforce that).
-- full_name     : display name. Postgres text is UTF-8 by default.
-- joined_at     : when the user first appeared. Always stored in UTC.
-- deleted_since : the soft-delete flag. NULL = active; a timestamp = the moment
--                 the user was soft-deleted. The ONLY nullable column.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT        NOT NULL,
    email         VARCHAR(200)  NOT NULL,
    full_name     VARCHAR(200)  NOT NULL,
    joined_at     TIMESTAMPTZ   NOT NULL,
    deleted_since TIMESTAMPTZ,
    PRIMARY KEY (id),
    UNIQUE (email)
);
